import type {
  AssessmentModeProfile,
  AssessmentModuleDefinition,
  ComboPresetDefinition,
} from "@/lib/assessment/catalog";

// Public selection metadata is release content. Trusted estimate/start routes
// revalidate every choice against PostgreSQL before any session is created.
export const publicAssessmentCatalog = {
  combos: [
    {
      description:
        "Profil Trait dan 16-Type untuk membaca kecenderungan umum dari dua lensa independen.",
      isFullSpectrum: false,
      key: "core_personality",
      moduleKeys: ["trait_profile", "type_16"],
      publicName: "Kenali Pola Dasar",
      recommendedMode: "standard",
      status: "published",
    },
    {
      description:
        "Motivasi, varian instingtual beta, dan attachment beta untuk refleksi pola dorongan dan kedekatan.",
      isFullSpectrum: false,
      key: "motivation_instinct",
      moduleKeys: ["enneagram", "instinct", "attachment"],
      publicName: "Motivasi dan Relasi",
      recommendedMode: "standard",
      status: "pilot",
    },
    {
      description:
        "Profil Trait, RIASEC beta, dan 16-Type untuk refleksi gaya belajar dan lingkungan kerja.",
      isFullSpectrum: false,
      key: "career_learning",
      moduleKeys: ["trait_profile", "riasec", "type_16"],
      publicName: "Belajar dan Karier",
      recommendedMode: "standard",
      status: "pilot",
    },
    {
      description:
        "16-Type, Temperamen, dan komunikasi Socionics-inspired eksperimental untuk gaya interaksi.",
      isFullSpectrum: false,
      key: "communication_relationship",
      moduleKeys: ["type_16", "temperament", "socionics_communication"],
      publicName: "Komunikasi",
      recommendedMode: "standard",
      status: "experimental",
    },
    {
      description:
        "Enam lensa (guarded beta) untuk mode Complex; item bank draft/pilot, bukan instrumen tervalidasi.",
      isFullSpectrum: false,
      key: "deep_self_discovery",
      moduleKeys: [
        "trait_profile",
        "type_16",
        "enneagram",
        "three_center",
        "temperament",
        "instinct",
      ],
      publicName: "Deep Self-Discovery",
      recommendedMode: "deep",
      status: "pilot",
    },
  ] satisfies ComboPresetDefinition[],
  modes: [
    {
      description: "Gambaran awal dengan coverage inti.",
      internalMode: "quick",
      isSelectable: true,
      maxItemsPerSegment: 120,
      provisionalPrecision: { max: 70, min: 60 },
      publicName: "Quick",
      secondsPerItem: 12,
      singleModuleItems: { max: 40, min: 24 },
      targetItems: { max: 60, min: 50 },
    },
    {
      description: "Pilihan utama dengan coverage dan consistency lebih baik.",
      internalMode: "standard",
      isSelectable: true,
      maxItemsPerSegment: 120,
      provisionalPrecision: { max: 85, min: 75 },
      publicName: "Normal",
      secondsPerItem: 12,
      singleModuleItems: { max: 70, min: 40 },
      targetItems: { max: 90, min: 80 },
    },
    {
      description: "Coverage mendalam dengan section dan kemungkinan multi-session.",
      internalMode: "deep",
      isSelectable: true,
      maxItemsPerSegment: 60,
      provisionalPrecision: { max: 92, min: 85 },
      publicName: "Complex",
      secondsPerItem: 15,
      singleModuleItems: { max: 100, min: 60 },
      targetItems: { max: 120, min: 100 },
    },
  ] satisfies AssessmentModeProfile[],
  modules: [
    {
      availabilityReason: null,
      category: "trait",
      defaultOrder: 10,
      description: "Lima spektrum kecenderungan untuk refleksi diri, bukan diagnosis.",
      evidenceTier: "A",
      isExperimental: false,
      isSelectable: true,
      key: "trait_profile",
      minimumAge: 13,
      modeQuota: { deep: 60, quick: 40, standard: 60 },
      publicName: "Profil Trait",
      releaseDisposition: "RELEASE_READY",
      status: "active",
      version: "modular-1",
    },
    {
      availabilityReason: null,
      category: "typology",
      defaultOrder: 20,
      description: "Empat kecenderungan pemrosesan yang dihitung dari item modul sendiri.",
      evidenceTier: "B",
      isExperimental: false,
      isSelectable: true,
      key: "type_16",
      minimumAge: 13,
      modeQuota: { deep: 48, quick: 32, standard: 40 },
      publicName: "16-Type Jungian-inspired",
      releaseDisposition: "RELEASE_READY",
      status: "published",
      version: "1.0.0",
    },
    {
      availabilityReason: null,
      category: "motivation",
      defaultOrder: 30,
      description: "Sembilan pola motivasi untuk refleksi, bukan instrumen resmi.",
      evidenceTier: "B",
      isExperimental: false,
      isSelectable: true,
      key: "enneagram",
      minimumAge: 15,
      modeQuota: { deep: 54, quick: 36, standard: 45 },
      publicName: "Lensa Motivasi Enneagram-inspired",
      releaseDisposition: "RELEASE_READY",
      status: "published",
      version: "1.0.0",
    },
    {
      availabilityReason: null,
      category: "motivation",
      defaultOrder: 40,
      description: "Pola head, heart, dan gut yang diukur dengan item independen.",
      evidenceTier: "B",
      isExperimental: false,
      isSelectable: true,
      key: "three_center",
      minimumAge: 15,
      modeQuota: { deep: 21, quick: 15, standard: 21 },
      publicName: "Pola Tiga Pusat",
      releaseDisposition: "RELEASE_READY",
      status: "pilot",
      version: "1.0.0",
    },
    {
      availabilityReason: null,
      category: "typology",
      defaultOrder: 50,
      description: "Refleksi energi, tempo, dan ekspresi emosi dari item modul sendiri.",
      evidenceTier: "B",
      isExperimental: false,
      isSelectable: true,
      key: "temperament",
      minimumAge: 13,
      modeQuota: { deep: 36, quick: 20, standard: 28 },
      publicName: "Lensa Temperamen",
      releaseDisposition: "RELEASE_READY",
      status: "published",
      version: "1.0.0",
    },
    {
      availabilityReason: null,
      category: "motivation",
      defaultOrder: 60,
      description: "Kecenderungan self-preservation, social, dan one-to-one.",
      evidenceTier: "B",
      isExperimental: false,
      isSelectable: true,
      key: "instinct",
      minimumAge: 15,
      modeQuota: { deep: 18, quick: 12, standard: 18 },
      publicName: "Lensa Varian Instingtual",
      releaseDisposition: "RELEASE_READY",
      status: "pilot",
      version: "1.0.0",
    },
    {
      availabilityReason: null,
      category: "communication",
      defaultOrder: 70,
      description: "Preferensi pemrosesan informasi dan interaksi dengan validasi terbatas.",
      evidenceTier: "B_EXPERIMENTAL",
      isExperimental: true,
      isSelectable: true,
      key: "socionics_communication",
      minimumAge: 15,
      modeQuota: { deep: 16, quick: 8, standard: 12 },
      publicName: "Komunikasi Socionics-inspired",
      releaseDisposition: "RELEASE_READY",
      status: "experimental",
      version: "1.0.0",
    },
    {
      availabilityReason: null,
      category: "career",
      defaultOrder: 80,
      description: "Enam dimensi minat dan contoh lingkungan belajar atau kerja.",
      evidenceTier: "B",
      isExperimental: false,
      isSelectable: true,
      key: "riasec",
      minimumAge: 15,
      modeQuota: { deep: 36, quick: 24, standard: 36 },
      publicName: "Minat Karier RIASEC",
      releaseDisposition: "RELEASE_READY",
      status: "pilot",
      version: "1.0.0",
    },
    {
      availabilityReason: null,
      category: "relationship",
      defaultOrder: 90,
      description: "Refleksi non-klinis tentang pola kedekatan dalam relasi.",
      evidenceTier: "B",
      isExperimental: false,
      isSelectable: true,
      key: "attachment",
      minimumAge: 18,
      modeQuota: { deep: 32, quick: 16, standard: 24 },
      publicName: "Refleksi Attachment",
      releaseDisposition: "RELEASE_READY",
      status: "pilot",
      version: "1.0.0",
    },
    {
      availabilityReason: null,
      category: "experimental",
      defaultOrder: 100,
      description: "Modul eksploratif yang tidak masuk confidence evidence-oriented.",
      evidenceTier: "EXPERIMENTAL",
      isExperimental: true,
      isSelectable: true,
      key: "psychosophy",
      minimumAge: 18,
      modeQuota: { deep: 20, quick: 12, standard: 16 },
      publicName: "Psychosophy Eksperimental",
      releaseDisposition: "RELEASE_READY",
      status: "experimental",
      version: "1.0.0",
    },
  ] satisfies AssessmentModuleDefinition[],
};
